### ISSUE TITLE
The Sullivan Doctoral Thesis Prize

### ISSUE THREAD

**Issue by UmarSpa** [BritishMachineVisionAssociation/BritishMachineVisionAssociation.github.io#2]
Hi, I have tried contacting BMVC organizers multiple times, but got no reply. So writing it here, hoping someone might reply.

I am trying to get an up to date info on The Sullivan Doctoral Thesis Prize. The regulation section at the bottom of the official [page](https://britishmachinevisionassociation.github.io/bursaries/sullivan-prize), mentions that the thesis has to be uploaded [here](https://britishmachinevisionassociation.github.io/theses). But this page doesn't exist.

Can you help ?

**Comment by Egmel** [comment]
Hi Umar,  apologies the committee have been rather tied up with the changes that have been required by the pandemic and a few things have been dropped.  We're in the process of restarting The Sullivan Doctoral Thesis Prize and hope to post an update about this later this year.
